### ISSUE TITLE
word option

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#119]
Question. -- if we are using the words option, then we have just one long sequence (i.e., an entire book etc). 
What does the last line of the following code do?
What about returning it as a RaggedTensor with just one entry?

```
 # get word count and set max_vocab_size
        if self.data_type == 'words':
            word_count = len(set(text))
            max_vocab = min(max_vocab, word_count) + 1
            word_index_list = list(zip(['UNK'] + list(unique_everseen(text)), range(1, word_count + 2)))
            sequences = [[x[1] - 1 for x in word_index_list if word in x[0]][0] for word in text]
```

**Comment by callahantiff** [comment]
This part of a manual way of deriving a list of lists that provides the word position for each word in a sentence. It was created in order to match the output from the built-in TF method that can only be applied to a list of lists.

Can you tell me a bit more about why you would want a RaggedTensor with a single entry returned here?  We do return a TF object using the code in lines 174-176. Maybe I am not understanding correctly?

**Comment by pnrobinson** [comment]
It seems that returning a Dataset object is suboptimal UNLESS we can figure out how to manipulate it without getting the warning about non-optimization. 
Also returning just a Python list would be possible here, since we are just transforming in the last line of this function and could do the transformation somewhere else, also, if we wanted to.

**Comment by callahantiff** [comment]
I see. OK, so it sounds like we are certain that the tf.Dataset object is responsible for that warning? If that's the case, perhaps the best immediate solution is to just return a list, like you mentioned, and convert it somewhere else. That would be an easy change to make.

**Comment by pnrobinson** [comment]
I will make this change in a branch called train3 (from the keras branch), and if things work I will make a PR, OK?

**Comment by callahantiff** [comment]
OK, that sounds great!

**Comment by pnrobinson** [comment]
done with the latest PR
