### ISSUE TITLE
Text encoder addition

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/N2V#149]
It would be good to be able to pass a CSV file to the text encoder where fields 1..(k-1) are some metadata and field k is a text (all in one line). Then we could do something like this

```
encoder = TextEncoder.fromCSV(file, payload_field=3, delim='\t')
```

The encoder would then return a list of lists for embedding. For instance, this will be useful for pubmed abstracts

**Comment by pnrobinson** [comment]
@vidarmehr @callahantiff @justaddcoffee 
PS -- we have two textencoder classes. (with and without _tf).
Which one should we keep?

**Comment by justaddcoffee** [comment]
I'd vote we keep the newer, shinier _tf version

(although are being used according to PyCharm. So, it'd probably require a PR with a little surgery to remove the non-tf version...)

**Comment by callahantiff** [comment]
We definitely want the new version (`_tf`). I can take a look later today and make a new PR. OK to do that on `develop`?

**Comment by vidarmehr** [comment]
Thank you, Tiffany. I am testing the branch that Deepak created. As soon as we merge it to develop which will be in an hour or so, then I think it would be ok to work on develop.

**Comment by callahantiff** [comment]
Sounds good @vidarmehr - would be willing to ping me when you think it's a good time for me to start working on that (and no rush on my end)? 😄

**Comment by vidarmehr** [comment]
@callahantiff Tiffany, I merged that branch to develop. Also, I have fixed number of epochs to 2 to get faster result. I am cleaning up the code. So, we will have num_epochs in parse_args().

**Comment by vidarmehr** [comment]
> @callahantiff Tiffany, I merged that branch to develop. Also, I have fixed number of epochs to 2 to get faster result. I am cleaning up the code. So, we will have num_epochs in parse_args().

@callahantiff Tiffany, so sorry. Let's wait until I merge my branch to develop, too. I will let you know when I am done.

**Comment by callahantiff** [comment]
@vidarmehr - I have taken care of the `text_encoder_tf` pointers. I updated the `__init__.py` file for now to point to the `text_encoder_tf.py` script rather than the original.  I did not want to delete the original `text_encoder.py` file, unless everyone thought that was OK. If we do go that route I can quickly update the naming to remove `_tf`. All of the current scripts that relied on this file seemed to already be pointing to the correct version (updated `_tf` version) so everything should still work fine 🤞. 

Let me know if you are OK with the changes as I described them here or if you would like me to remove the original file (and test) and update the naming of the new file to remove `_tf`. If you are happy with the change I made, then I believe that this issue can be closed.

**Comment by vidarmehr** [comment]
@callahantiff Thank you, Tiffany. I agree with the changes. I also tested the code to make sure that everything works well. Please delete the original one and then remove _tf, so we have only one text_encoder.py file which is the tf version.

**Comment by callahantiff** [comment]
@vidarmehr - done! Can we close this?

**Comment by vidarmehr** [comment]
Thank you, Tiffany!
